# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: freefire_response.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'freefire_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66reefire_response.proto\"`\n\tInnerData\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\r\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\r\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\r\x12\x0f\n\x07\x66ield_7\x18\x07 \x01(\r\x12\x0f\n\x07\x66ield_8\x18\x08 \x01(\r\"\x99\x01\n\x10\x46reeFireResponse\x12\x1b\n\x07\x66ield_1\x18\x01 \x01(\x0b\x32\n.InnerData\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\r\x12\x0f\n\x07\x66ield_8\x18\x08 \x01(\r\x12\x10\n\x08\x66ield_16\x18\x10 \x01(\r\x12\x10\n\x08\x66ield_22\x18\x16 \x01(\t\x12\x10\n\x08\x66ield_23\x18\x17 \x01(\x11\x12\x10\n\x08\x66ield_24\x18\x18 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'freefire_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INNERDATA']._serialized_start=27
  _globals['_INNERDATA']._serialized_end=123
  _globals['_FREEFIRERESPONSE']._serialized_start=126
  _globals['_FREEFIRERESPONSE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
